### ISSUE TITLE
Bug in get-and-preprocess-data ?

### ISSUE THREAD

**Issue by MikeWangWZHL** [smartschat/tilse#5]
Hi, thanks for sharing this awesome codebase.

I think I might spotted a potential bug in the preprocessing code: **get-and-preprocess-data**

In the current code, from this [line](https://github.com/smartschat/tilse/blob/bd6706f13a55b4da47ae456b6634064c3d3b5d4f/bin/get-and-preprocess-data#L81 ) you started to copy over files from Timeline17 dataset, with the assumption that there will be no duplicated file name within each topic and data dir. 
However I do found that there are identically named files from different publisher within the same date of a certain topic. For example: For example, on data 2011-03-03 in topic LibyaWar, there are two documents with identical name "95.thm.txt" in LibyaWar_cnn and LibyaWar_reuters. Using the current version of the preprocessing code results in dropping one of the two documents.

Let me know if this makes sense, thank you!

And I am actually not sure why you want to group news articles from different publisher on the same date of the same topic together.  Could you please elaborate a bit on this? Thank you!

**Comment by smartschat** [comment]
Hi Mike, thank you for spotting the bug, this indeed was not intended. I will work on a fix.

For grouping news articles from different publishers together, note that this was the approach taken by [Tran et al.](https://www.eelcoherder.com/images/publications/2015/ecir2015_timeline_summarization.pdf) when constructing the *crisis* dataset: given a topic, timelines from well-known news agencies were selected, and news articles from these agencies relevant to the topic were crawled. For each topic, all timelines and news articles were grouped together. For simplicity and to have more general experimental settings, we opted to treat *timeline17* and *crisis* in the same way. (The grouping could also give a more comprehensive view on the subject, since timelines provided by an agency aren't necessarily restricted to information that can be found in articles from the agency.)

Thank you for your question, we should have made this clearer in the paper. It would also be interesting to see how performance changes for *timeline17* when the corpus is restricted to news articles from the same agency as the timeline.

**Comment by MikeWangWZHL** [comment]
Thanks for the clarification!
